### ISSUE TITLE
"msg": "unable to find /root/.my.cnf. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using ********: YES)\")"

### ISSUE THREAD

**Issue by SalahAdDin** [OpenSaasAU/edx-docker-ansible#11]
I having this problem now.

This is the log:
[build.txt](https://github.com/OpenSaasAU/edx-docker-ansible/files/1139256/build.txt)

Searching in the code i found this:
```yaml
- name: create databases
  mysql_db:
    db: "{{ item }}"
    login_host: "{{ DB_MYSQL_HOST }}"
    login_user: "{{ COMMON_MYSQL_MIGRATE_USER }}"
    login_password: "{{ COMMON_MYSQL_MIGRATE_PASS }}"
    state: present
    encoding: utf8
  when: item != None and item != ''
  with_items: "{{ edxlocal_databases }}"
  tags:
    - install
    - install:configuration
```

This is the code in `main.yml` in the `docker_setup_db` playbook.

And this is the password's value: `COMMON_MYSQL_MIGRATE_PASS: 'password'`.

So, what's the problem?
